banner_background_color:
default: "white"
  type: string
  description: "This will change the background color of the banner. Enter valid CSS colours or hex values (including the #)."

banner_text_color:
  default: "black"
  type: string
  description: "This will change the text color of the banner. Enter valid CSS colours or hex values (including the #)."

banner_border_color:
  default: "black"
  type: string
  description: "This will change the border color of the banner. Enter valid CSS colours or hex values (including the #)."

banner_border_thickness:
  default: 3
  type: integer
  description: "This will change the border thickness of the banner. All numbers are in pixels (px)."

banner_text_content:
  default: "SAMPLE BANNER TEXT"
  type: string
  textarea: true
  description: "This will change the text of the banner."

banner_visible:
  default: show
  type: enum
  choices:
    - show
    - hide
  description: "'show' for banner to be visible; 'hide' for it to be hidden."

banner_position:
  default: above-site-header
  type: enum
  choices:
    - above-site-header
    - below-site-header
    - above-main-containter
  description: "The location of the banner."
