banner_background_color:
  default: white
  type: enum
  choices:
    - black
    - silver
    - gray
    - white
    - maroon
    - red
    - purple
    - green
    - lime
    - olive
    - yellow
    - navy
    - blue
    - teal
    - aqua
  description: "This will change the background color of the banner."

banner_text_color:
  default: "black"
  type: textarea-true

  description: "This will change the text color of the banner."

banner_text_content:
  default: "SAMPLE BANNER TEXT"
  type: string
  description: "This will change the text of the banner."

banner_visible:
  default: show
  type: enum
  choices:
    - show
    - hide
  description: "'show' for banner to be visible; 'hide' for it to be hidden."
