banner_background_color:
  default: white
  type: enum
  choices:
  - black
  - silver
  - gray
  - white
  - maroon
  - red
  - purple
  - green
  - lime
  - olive
  - yellow
  - navy
  - blue
  - teal
  - aqua
  description: "This will change the background color of the banner."

banner_text_color:
  default: black
  type: string
  description: "This will change the text color of the banner."

banner_text_content:
  default: "SAMPLE BANNER TEXT"
  type: string
  description: "This will change the text of the banner."

banner_visible:
  default: block
  type: enum
  choices:
    - block
    - none
  description: "'block' for banner to be visible; 'none' for it to be hidden."
